const ActivityEntityType = {
  PROJECT: "project",
  ISSUE: "issue",
  SPRINT: "sprint",
  COMMENT: "comment",
  ATTACHMENT: "attachment",
  MEMBER: "member",
  LABEL: "label",
  VERSION: "version",
  COMPONENT: "component",
  CHECKLIST: "checklist",
  TIMELOG: "timelog",
};

const ActivityAction = {
  CREATE:           "create",
  UPDATE:           "update",
  DELETE:           "delete",
  ARCHIVE:          "archive",
  RESTORE:          "restore",
  DUPLICATE:        "duplicate",
  MOVE:             "move",
  REORDER:          "reorder",
  ASSIGN:           "assign",
  UNASSIGN:         "unassign",
  CHANGE_STATUS:    "change_status",
  CHANGE_PRIORITY:  "change_priority",
  CHANGE_SPRINT:    "change_sprint",
  ADD_MEMBER:       "add_member",
  REMOVE_MEMBER:    "remove_member",
  ADD_WATCHER:      "add_watcher",
  REMOVE_WATCHER:   "remove_watcher",
  UPLOAD_FILE:      "upload_file",
  REMOVE_FILE:      "remove_file",
  CREATE_COMMENT:   "create_comment",
  UPDATE_COMMENT:   "update_comment",
  DELETE_COMMENT:   "delete_comment",
  ADD_CHECKLIST:    "add_checklist",
  UPDATE_CHECKLIST: "update_checklist",
  DELETE_CHECKLIST: "delete_checklist",
};

module.exports = {
  ActivityEntityType,
  ActivityAction,
};
